### PR TITLE
HADotNet - fix for states API

### PR DESCRIPTION
**Pull request by imalkevich**
Hi Jake,

Hope you are doing well.

I noticed a minor issue with states API - would you please take a look and merge once you have time?

Thanks

### CODE REVIEW

**Comment by qJake** [comment]
Have a look at:

https://github.com/qJake/HADotNet/blob/e4f6d97bd26d7b80b0091da434de706019d868a3/HADotNet.Core/BaseClient.cs#L63

In `BaseClient`, when `Post<T>` is called, there is an optional parameter for `isRawBody` which by default is `false`.

Therefore, in the `StatesClient`, when `Post` is called with the anonymous object `new { ... }`, it is serialized by the base client.

Feel free to open an issue if you think this behavior isn't working, and/or try a unit test to see what's going on.

**Comment by imalkevich** [comment]
Hi Jake,

Yes, you are right, but without the changes that I'm suggesting the code is sending a string `Newtonsoft.Json.JsonConvert.SerializeObject(new { state = newState, attributes = setAttributes })` and `isRawBody =false`, which leads string to be serialized the second time in `BaseClient` (because `isRawBody = false`).

Please let me know if you need more details - I can provide more code examples with screenshots.

Thanks

**Comment by qJake** [comment]
Oh I see! Yes, I'm sorry, I read that wrong.

Thanks for fixing this! I will try and do a release soon that includes this.

**Comment by imalkevich** [comment]
Thanks a lot Jake!

**Comment by qJake** [comment]
@imalkevich Sorry for the delay, v1.3.1 has just been published with these changes!

**Comment by imalkevich** [comment]
Hi Jake (@qJake ) ,

Great, thank you and thanks for the heads-up!

Thanks

**Pull request merged**
