### PR TITLE
HADotNet - adding Info and Stats clients

### PR DESCRIPTION
**Pull request by imalkevich**
Hi Jake,

Hope you and your family are doing well these days.

I prepared one merge request for working with Home Assistant information and statistics:
image

Hope you will have time to look at the changes and merge them into the main branch.

For sure please let me know if you will have questions and/or comments to the changes.

Thanks

### CODE REVIEW

**Comment by qJake** [comment]
Hi @imalkevich, this looks really good. Do you have any links to the documentation for this on Home Assistant's website that I could review? Or is this all reverse-engineered?

Lastly, have you tested the behavior when you attempt to use this code on a non-supervised (e.g. just "Core") environment? I'd imagine those endpoints don't exist, I'm wondering if there's a graceful way to handle that, like maybe throwing a custom `SupervisorNotFoundException` or something similar.

**Comment by imalkevich** [comment]
Hi Jake, @qJake 

As for the documentation - to be honest this is reversed-engineered, I looked at the https://developers.home-assistant.io/docs/api/rest and there are no such details, so I just looked at the page and checked the requests that are being sent and responses coming... Not ideal I agree, but this is the way at least...

And no, I haven't tested this in non-supervised environment unfortunately... Agree it would be nice to throw `SupervisorNotFoundException`, but I'm not sure how to check if installation is non-supervised or not, probably making additional request might be costly, or maybe it should be part of Client constructor, then constructor would be 'heavy'... So not sure Jake, I would say it is up to you to weight on it...

Thanks

**Comment by qJake** [comment]
Sounds good, I'll make just a few tweaks and see if I can test it on a Core instance... thanks!

**Comment by qJake** [comment]
FYI - I found a way to detect a Supervisor vs. Core install and test for it, so I added that.

Your changes are now live in v1.5.0! Thanks again!

https://www.nuget.org/packages/HADotNet.Core/1.5.0

**Comment by imalkevich** [comment]
Hi Jake,

Great! Thank you for a quick turn around on this!

Thanks

**Pull request merged**
